version: '3.4'

services:
  samplewebapplication:
    #image: ${DOCKER_REGISTRY-}samplewebapplication
    image: samplegroupacr.azurecr.io/samplewebapplication
    build:
      context: .\SampleWebApplication
      dockerfile: Dockerfile
